site_name: BetterAPI
theme:
  logo: images/Rikka.png
  favicon: images/Rikka.png
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple
copyright: Made by Nonamegone
repo_url: https://github.com/Nonamegone/betterapi
repo_name: BetterAPI
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav: 
  - Introduction: index.md
  - File system: fs.md
  - Input: input.md
  - Draw: draw.md
  - Entity list: entlist.md
  - Source engine: sengine.md
  - Memory: memory.md
  - Panorama: panorama.md
  - Misc: misc.md
  - Classes:
    - Player: classes/player.md
  - Example: examples.md