site_name: BetterAPI
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple
    logo: images/Rikka.png
    favicon: images/Rikka.png
copyright: Почему нет?
repo_url: https://github.com/Nonamegone/betterapi
repo_name: BetterAPI
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav: 
  - Introduction: index.md
  - File System: fs.md
  - Input: input.md
  - Draw: draw.md
  - Source Engine: sengine.md
  - Memory: memory.md
  - Panorama: panorama.md
  - Misc: misc.md
  - Example: examples.md